name: Scheduled

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

env:
  GH_TOKEN: ${{ github.token }}
  USERNAME: bjornnorgaard

jobs:
  scheduled:
    name: Handle pull-requests
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - run: go run main.go github approve-dependabot
